# permissions for end users to edit nonadminbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nonadminbackup-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nac-operator
    app.kubernetes.io/part-of: nac-operator
    app.kubernetes.io/managed-by: kustomize
  name: nonadminbackup-editor-role
rules:
- apiGroups:
  - oadpnac.openshift.io
  resources:
  - nonadminbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oadpnac.openshift.io
  resources:
  - nonadminbackups/status
  verbs:
  - get
