apiVersion: oadpnac.openshift.io/v1alpha1
kind: NonAdminRestore
metadata:
  labels:
    app.kubernetes.io/name: nonadminrestore
    app.kubernetes.io/instance: nonadminrestore-sample
    app.kubernetes.io/part-of: nac-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: nac-operator
  name: nonadminrestore-sample
spec:
  # TODO(user): Add fields here
